package org.pocketworkstation.pckeyboard

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/** The emoji data, search and recents as pure logic (Droidtop/tracker#342). */
class EmojiTest {
    private val sample = """
        # Auto-generated by emojicon.py using CLDR v48
        # DO NOT EDIT MANUALLY!

        [smileys_emotion]
        😀;grinning face;cheerful|face|grin|happy|smile
        😂;face with tears of joy;face|joy|laugh|tear
        🙂;slightly smiling face;face|smile
        [people_body]
        👋;waving hand;bye|hand|hello|wave
        ${'\t'}👋🏻;waving hand: light skin tone;bye|hand|hello|wave
        [flags]
        🇳🇴;flag: Norway;flag|norway
    """.trimIndent()

    @Test fun parsingKeepsGroupsInOrderAndLeavesSkinToneVariantsOut() {
        val catalog = EmojiCatalog.parse(sample)
        assertEquals(listOf("smileys_emotion", "people_body", "flags"), catalog.groups.map { it.id })
        assertEquals(listOf("😀", "😂", "🙂"), catalog.groups[0].entries.map { it.emoji })
        assertEquals(1, catalog.groups[1].entries.size)
        assertEquals("waving hand", catalog.groups[1].entries[0].name)
        assertEquals(listOf("bye", "hand", "hello", "wave"), catalog.groups[1].entries[0].keywords)
    }

    @Test fun searchRanksTheNameFirstThenWordsThenKeywords() {
        val catalog = EmojiCatalog.parse(sample)
        // A name that starts with "face" comes before names with "face" as a later word; data order within a rank.
        assertEquals(listOf("😂", "😀", "🙂"), catalog.search("face").map { it.emoji })
        // The name starts with "slightly": a prefix match beats the others.
        assertEquals("🙂", catalog.search("slightly").first().emoji)
        // "joy" is a word of one name; "hello" only a keyword.
        assertEquals(listOf("😂"), catalog.search("joy").map { it.emoji })
        assertEquals(listOf("👋"), catalog.search("hello").map { it.emoji })
    }

    @Test fun everyWordOfTheQueryHasToMatch() {
        val catalog = EmojiCatalog.parse(sample)
        assertEquals(listOf("😀"), catalog.search("grin happy").map { it.emoji })
        assertTrue(catalog.search("grin sad").isEmpty())
        assertTrue(catalog.search("   ").isEmpty())
    }

    @Test fun searchIsCaseInsensitiveAndBounded() {
        val catalog = EmojiCatalog.parse(sample)
        assertEquals(listOf("🇳🇴"), catalog.search("NORWAY").map { it.emoji })
        assertEquals(1, catalog.search("face", limit = 1).size)
    }

    @Test fun recentsAreNewestFirstWithoutRepeatsAndBounded() {
        var recent = emptyList<String>()
        for (e in listOf("a", "b", "c", "a")) recent = EmojiRecents.push(recent, e)
        assertEquals(listOf("a", "c", "b"), recent)
        assertEquals(listOf("x", "a"), EmojiRecents.push(listOf("a", "b"), "x", max = 2))
        assertEquals(recent, EmojiRecents.decode(EmojiRecents.encode(recent)))
        assertFalse(EmojiRecents.decode(null).any())
    }
}
