package dev.droidtop.stores.itch

import android.content.Context

/**
 * itch.io API endpoints and the sign-in file.
 *
 * Auth is the user's own personal API key (Bearer token), generated by the
 * user themselves at https://itch.io/user/settings under "API Keys" --
 * droidtop never creates an account or a key on the user's behalf, only
 * stores the key the user typed into a settings row.
 *
 * **Documented, official endpoints** (https://itch.io/docs/api/serverside):
 * - `GET /profile` (scope `profile:me`) -- verifies the key and returns the
 *   signed-in user.
 * - `GET /profile/owned-keys` (scope `profile:owned`) -- every download key
 *   the user holds (purchases, claims, bundles, gifts), each naming its
 *   game.
 *
 * **Undocumented but stable, reverse-engineered endpoints** -- itch's own
 * public API reference has no path to list a game's uploads or resolve a
 * real download URL for one (confirmed against both the current and the
 * "legacy" serverside API reference pages, 2026-09-27); the official itch
 * app and `butler` use private endpoints for this. The two used here are
 * the same ones the open-source downloader itch-dl relies on
 * (https://github.com/DragoonAethis/itch-dl, `itch_dl/downloader.py`):
 * - `GET /games/{game_id}/uploads?download_key_id={key}` -- the uploads
 *   (platform builds) for one owned game.
 * - `GET /uploads/{upload_id}/download?download_key_id={key}` -- resolves
 *   to JSON carrying the real, time-limited download URL for that upload.
 *
 * Because these two are not part of itch's documented contract they could
 * change without notice; [ItchApiClient] treats a shape it does not
 * recognise as a failure to sync rather than a crash.
 *
 * Lifted from droidtop's fork of GameNative (app.gamenative.service.itch,
 * GPL-3.0). Where a game installs is no longer decided here: the install
 * job hands the store the folder the person picked (docs/SPEC.md 7g,
 * "Stores").
 */
internal object ItchConstants {
    const val ITCH_API_BASE = "https://api.itch.io"

    /** Where the person makes the key droidtop asks for. */
    const val API_KEY_PAGE = "https://itch.io/user/settings/api-keys"

    /** Where the user's raw API key file lives: the same file GameNative used, so a sign-in survives the move. */
    fun getAuthConfigPath(context: Context): String = "${context.filesDir}/itch_auth.json"
}
