#!/usr/bin/env python3
"""Regenerates SdlControllerIds.kt from SDL's controller list.

Usage: gen_sdl_controller_families.py <controller_list.h> <SDL commit> > SdlControllerIds.kt

controller_list.h is src/joystick/controller_list.h of https://github.com/libsdl-org/SDL
(branch SDL2), Valve's table of USB vendor/product ids by controller type that
SDL's SDL_GetJoystickGameControllerTypeFromVIDPID classifies through. zlib licence,
see NOTICE.md. Only the ids are taken; the grouping into the three printed
face-button families is droidtop's (docs/SPEC.md 7b).
"""
import re
import sys

XBOX = {"XBox360Controller", "XBoxOneController"}
PLAYSTATION = {"PS3Controller", "PS4Controller", "PS5Controller", "XInputPS4Controller"}
NINTENDO = {
    "SwitchProController", "SwitchInputOnlyController", "SwitchJoyConLeft",
    "SwitchJoyConRight", "SwitchJoyConPair", "XInputSwitchController",
}

rows = {"XBOX": [], "PLAYSTATION": [], "NINTENDO": []}
pattern = re.compile(r"^\s*\{ MAKE_CONTROLLER_ID\( (0x[0-9a-fA-F]+), (0x[0-9a-fA-F]+) \), k_eControllerType_(\w+),")
for line in open(sys.argv[1], encoding="utf-8"):
    match = pattern.match(line)
    if not match:
        continue
    vid, pid, kind = match.group(1).lower(), match.group(2).lower(), match.group(3)
    family = "XBOX" if kind in XBOX else "PLAYSTATION" if kind in PLAYSTATION else "NINTENDO" if kind in NINTENDO else None
    # SDL answers vendor 0 and 1 itself (by name, or as unknown) before this table.
    if family and int(vid, 16) > 1:
        rows[family].append((int(vid, 16), int(pid, 16)))


def array(name, items):
    out = ["    private val %s = longArrayOf(" % name]
    items = sorted(set(items))
    for i in range(0, len(items), 6):
        chunk = ", ".join("0x%04x%04xL" % item for item in items[i:i + 6])
        out.append("        " + chunk + ",")
    out.append("    )")
    return "\n".join(out)


print("""package dev.droidtop.library.controller

/**
 * GENERATED by build-scripts/gen_sdl_controller_families.py from SDL's
 * src/joystick/controller_list.h (SDL2 branch, commit %s), Valve's table
 * of USB vendor and product ids by controller type, which SDL's
 * `SDL_GetJoystickGameControllerTypeFromVIDPID` classifies through.
 * Copyright (C) Valve Corporation, zlib licence (NOTICE.md). Do not edit
 * by hand: regenerate. Each entry is `vendorId shl 16 or productId`.
 *
 * Grouped by what is printed on the face buttons: Xbox 360 and Xbox One
 * types are [GlyphFamily.XBOX]; PS3, PS4, PS5 and DualShock-over-XInput are
 * [GlyphFamily.PLAYSTATION]; Switch Pro, input-only Switch clones and
 * Joy-Con are [GlyphFamily.NINTENDO]. Ids SDL does not list are not here.
 */
internal object SdlControllerIds {
%s

%s

%s

    fun familyOf(vendorId: Int, productId: Int): GlyphFamily? {
        val id = (vendorId.toLong() shl 16) or productId.toLong()
        return when {
            xbox.contains(id) -> GlyphFamily.XBOX
            playstation.contains(id) -> GlyphFamily.PLAYSTATION
            nintendo.contains(id) -> GlyphFamily.NINTENDO
            else -> null
        }
    }
}""" % (sys.argv[2], array("xbox", rows["XBOX"]), array("playstation", rows["PLAYSTATION"]), array("nintendo", rows["NINTENDO"])))
