package dev.droidtop.runtime.linux.root

import java.io.File

/**
 * Maps onto vendor/droidspaces' documented `.config` file format exactly
 * (see Documentation/Linux-CLI.md's "Configuration Files" section) — every
 * field name here matches a real `key=value` line the `droidspaces` CLI
 * parses via `--conf=`. Deliberately not a general-purpose config
 * abstraction: this is a straight transcription of that one format.
 */
data class DroidSpacesContainerConfig(
    val name: String,
    val hostname: String = name,
    val rootfsPath: String,
    val bindMounts: List<Pair<String, String>> = emptyList(), // host:container
    val envFilePath: String? = null,
    val volatileMode: Boolean = false, // we want persistent containers, not RAM-only
    val enablePulseAudio: Boolean = true, // DroidSpaces' own host<->container audio bridge, no design work needed on our side
    val enableGpuMode: Boolean = true, // GPU device nodes only, not full --hw-access
    val foreground: Boolean = false,
) {
    fun toConfigText(): String = buildString {
        appendLine("# Droidspaces container config, generated by DroidTop — do not hand-edit,")
        appendLine("# regenerated on every DroidSpacesRuntime.createPrimary()/createSibling() call.")
        appendLine("name=$name")
        appendLine("hostname=$hostname")
        appendLine("rootfs_path=$rootfsPath")
        if (bindMounts.isNotEmpty()) {
            appendLine("bind_mounts=" + bindMounts.joinToString(",") { (src, dst) -> "$src:$dst" })
        }
        envFilePath?.let { appendLine("env_file=$it") }
        appendLine("volatile_mode=${if (volatileMode) 1 else 0}")
        appendLine("enable_pulseaudio=${if (enablePulseAudio) 1 else 0}")
        appendLine("enable_gpu_mode=${if (enableGpuMode) 1 else 0}")
        appendLine("foreground=${if (foreground) 1 else 0}")
    }

    fun writeTo(file: File) {
        file.parentFile?.mkdirs()
        file.writeText(toConfigText())
    }
}
