#include "wayland_client.h"
#include "default_keymap.h"

#include <android/log.h>
#include <android/native_window.h>
#include <android/sharedmem.h>
#include <wayland-client.h>

#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <mutex>
#include <pthread.h>
#include <signal.h>
#include <string>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

// Generated by wayland-scanner at build time from vendor/wlroots/protocol —
// see ../CMakeLists.txt. Not present until that codegen step has actually
// been run with wayland-scanner on the PATH.
#include "wlr-screencopy-unstable-v1-client-protocol.h"
#include "wlr-virtual-pointer-unstable-v1-client-protocol.h"
#include "virtual-keyboard-unstable-v1-client-protocol.h"
#include "ext-data-control-v1-client-protocol.h"

#define LOG_TAG "hostbridge/wl"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)

namespace hostbridge {

// Globals bound off the primary container compositor's registry. compositor/
// seat/screencopy/virtual-pointer/virtual-keyboard are required — if the
// compositor doesn't advertise all of them, connect() fails. output/shm are
// tracked too (needed for screencopy) but their absence isn't fatal at
// connect() time since a headless compositor might advertise its first
// output slightly later; presentPrimaryOutput() checks for them itself.
struct WaylandGlobals {
    wl_compositor* compositor = nullptr;
    wl_seat* seat = nullptr;
    wl_shm* shm = nullptr;
    zwlr_screencopy_manager_v1* screencopy_manager = nullptr;
    zwlr_virtual_pointer_manager_v1* virtual_pointer_manager = nullptr;
    zwp_virtual_keyboard_manager_v1* virtual_keyboard_manager = nullptr;

    // Clipboard. NOT required at connect() time, unlike the five above: a
    // compositor without it still gives a usable desktop, just one whose
    // selection doesn't cross into Android. See ClipboardState below and
    // ../README.md for why this protocol rather than wl_data_device.
    ext_data_control_manager_v1* data_control_manager = nullptr;

    // MVP: track only the first wl_output seen — matches the current
    // single-merged-desktop default (DisplayOutput.kt / SPEC.md §4). A real
    // multi-output implementation needs a list here plus a way for the
    // Kotlin side to pick which one presentPrimaryOutput() targets; that's
    // genuine future work, not an oversight.
    wl_output* output = nullptr;

    zwlr_virtual_pointer_v1* virtual_pointer = nullptr;
    zwp_virtual_keyboard_v1* virtual_keyboard = nullptr;
};

// Live state for one in-progress (or steady-state looping) screencopy
// capture session targeting a single ANativeWindow. Holds its own
// manager/output/shm (copied from WaylandGlobals when the session starts)
// so the frame-listener callbacks below — free functions, no access to
// WaylandClient — can re-arm the next capture themselves without reaching
// back through global state.
struct OutputCapture {
    ANativeWindow* window = nullptr;

    zwlr_screencopy_manager_v1* manager = nullptr;
    wl_output* output = nullptr;
    wl_shm* shm = nullptr;

    zwlr_screencopy_frame_v1* frame = nullptr;

    // shm buffer, reused across frames unless the compositor reports a size
    // change (only reallocated when width/height/stride actually differ).
    wl_shm_pool* pool = nullptr;
    wl_buffer* buffer = nullptr;
    int shmFd = -1;
    void* shmData = nullptr;
    size_t shmSize = 0;

    uint32_t width = 0;
    uint32_t height = 0;
    uint32_t stride = 0;
    uint32_t format = 0; // enum wl_shm_format
    bool haveBufferInfo = false;

    bool running = false;
};

/**
 * Live clipboard state for one connection, over ext-data-control-v1.
 *
 * Why this protocol and not wl_data_device: wl_data_device only delivers a
 * selection to the client that currently holds keyboard focus on one of its
 * own surfaces. host-bridge has NO surface at all — it is a screencopy +
 * virtual-input client, deliberately (see this file's header comment and
 * HostBridge.kt) — so wl_data_device is structurally unavailable to it, not
 * merely inconvenient. ext-data-control-v1 exists for exactly this case: a
 * privileged client that observes and sets the selection without focus,
 * which is the clipboard-manager role.
 *
 * Threading: `mutex` guards everything a non-dispatch thread can touch.
 * offerClipboardText() runs on whatever thread Android's clipboard listener
 * fired on; the source/offer callbacks run on the dispatch thread; the
 * actual pipe reads and writes run on short-lived detached workers so that
 * neither a slow container-side reader nor a large payload can stall the
 * dispatch loop (which also drives every screencopy frame).
 */
struct ClipboardState {
    struct wl_display* display = nullptr;
    ext_data_control_manager_v1* manager = nullptr;
    ext_data_control_device_v1* device = nullptr;

    std::mutex mutex;

    /** What our source hands out when the compositor asks for it. */
    std::string offeredText;

    /**
     * The source backing our current claim on the selection. A source may
     * only be passed to set_selection once (ext_data_control_device_v1's
     * `used_source` error), so every push creates a fresh one and the
     * previous is destroyed after the new claim lands.
     */
    ext_data_control_source_v1* source = nullptr;

    /**
     * The offer named by the most recent `selection` event. Deliberately
     * NOT destroyed as soon as receive() is issued: the transfer is still
     * being serviced at that point. It is destroyed when the next selection
     * replaces it, and in disconnect().
     */
    ext_data_control_offer_v1* currentOffer = nullptr;

    ClipboardTextCallback callback = nullptr;
    void* callbackUserData = nullptr;

    /** Set by the device's `finished` event — the compositor tore it down. */
    bool finished = false;
};

namespace {

// ---- registry ----

void registry_global(void* data, wl_registry* registry, uint32_t name,
                      const char* interface, uint32_t version) {
    auto* globals = static_cast<WaylandGlobals*>(data);

    if (std::strcmp(interface, wl_compositor_interface.name) == 0) {
        globals->compositor = static_cast<wl_compositor*>(
            wl_registry_bind(registry, name, &wl_compositor_interface, 4));
    } else if (std::strcmp(interface, wl_seat_interface.name) == 0) {
        globals->seat = static_cast<wl_seat*>(
            wl_registry_bind(registry, name, &wl_seat_interface, 7));
    } else if (std::strcmp(interface, wl_shm_interface.name) == 0) {
        globals->shm = static_cast<wl_shm*>(
            wl_registry_bind(registry, name, &wl_shm_interface, 1));
    } else if (std::strcmp(interface, wl_output_interface.name) == 0) {
        if (!globals->output) { // first one only — see OutputCapture's comment
            globals->output = static_cast<wl_output*>(
                wl_registry_bind(registry, name, &wl_output_interface, 2));
        }
    } else if (std::strcmp(interface, zwlr_screencopy_manager_v1_interface.name) == 0) {
        globals->screencopy_manager = static_cast<zwlr_screencopy_manager_v1*>(
            wl_registry_bind(registry, name, &zwlr_screencopy_manager_v1_interface, version));
    } else if (std::strcmp(interface, zwlr_virtual_pointer_manager_v1_interface.name) == 0) {
        globals->virtual_pointer_manager = static_cast<zwlr_virtual_pointer_manager_v1*>(
            wl_registry_bind(registry, name, &zwlr_virtual_pointer_manager_v1_interface, version));
    } else if (std::strcmp(interface, zwp_virtual_keyboard_manager_v1_interface.name) == 0) {
        globals->virtual_keyboard_manager = static_cast<zwp_virtual_keyboard_manager_v1*>(
            wl_registry_bind(registry, name, &zwp_virtual_keyboard_manager_v1_interface, version));
    } else if (std::strcmp(interface, ext_data_control_manager_v1_interface.name) == 0) {
        // Pinned to version 1 rather than `version`: vendor/sway creates
        // this global with version 1 (sway/server.c's
        // wlr_ext_data_control_manager_v1_create(display, 1)), and binding
        // above what the compositor offers is a protocol error, not a
        // graceful degradation.
        globals->data_control_manager = static_cast<ext_data_control_manager_v1*>(
            wl_registry_bind(registry, name, &ext_data_control_manager_v1_interface, 1));
    }
}

void registry_global_remove(void* /* data */, wl_registry* /* registry */, uint32_t /* name */) {
    // TODO: handle the primary container's compositor restarting mid-session
    // (a global disappearing) — currently unhandled, connection just goes stale.
}

constexpr wl_registry_listener kRegistryListener = {
    .global = registry_global,
    .global_remove = registry_global_remove,
};

// ---- screencopy ----

void startNextCapture(OutputCapture* cap); // fwd decl — frame_ready/frame_failed below re-arm via this

void allocateShmBuffer(OutputCapture* cap) {
    size_t size = static_cast<size_t>(cap->stride) * cap->height;
    if (cap->buffer && size == cap->shmSize) {
        return; // reuse — dimensions unchanged since last frame
    }

    if (cap->buffer) {
        wl_buffer_destroy(cap->buffer);
        cap->buffer = nullptr;
    }
    if (cap->pool) {
        wl_shm_pool_destroy(cap->pool);
        cap->pool = nullptr;
    }
    if (cap->shmData) {
        munmap(cap->shmData, cap->shmSize);
        cap->shmData = nullptr;
    }
    if (cap->shmFd >= 0) {
        close(cap->shmFd);
        cap->shmFd = -1;
    }

    // ASharedMemory (Android's memfd_create equivalent, NDK API 26+) rather
    // than shm_open — gives us an fd wl_shm can mmap over the Wayland
    // connection exactly like a normal Linux memfd would.
    int fd = ASharedMemory_create("hostbridge-screencopy", size);
    if (fd < 0) {
        LOGE("ASharedMemory_create(%zu) failed", size);
        return;
    }

    void* data = mmap(nullptr, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (data == MAP_FAILED) {
        LOGE("mmap failed for screencopy shm buffer: %s", strerror(errno));
        close(fd);
        return;
    }

    cap->shmFd = fd;
    cap->shmData = data;
    cap->shmSize = size;
    cap->pool = wl_shm_create_pool(cap->shm, fd, static_cast<int32_t>(size));
    cap->buffer = wl_shm_pool_create_buffer(
        cap->pool, 0, static_cast<int32_t>(cap->width), static_cast<int32_t>(cap->height),
        static_cast<int32_t>(cap->stride), static_cast<wl_shm_format>(cap->format));
}

// Copies the just-captured shm frame onto the target ANativeWindow, with a
// naive per-pixel BGRA<->RGBA channel swap: wl_shm's common format
// (WL_SHM_FORMAT_ARGB8888/XRGB8888) is native-endian 0xAARRGGBB, i.e. bytes
// B,G,R,A on a little-endian device — Android's WINDOW_FORMAT_RGBA_8888 is
// bytes R,G,B,A. Correct, not optimized: fine for a first working version,
// worth revisiting (GPU blit / shader) once this is actually running against
// a live compositor and framerate is measurable.
void blitFrameToWindow(OutputCapture* cap) {
    if (!cap->window || !cap->shmData) return;

    ANativeWindow_setBuffersGeometry(cap->window, static_cast<int32_t>(cap->width),
                                      static_cast<int32_t>(cap->height), WINDOW_FORMAT_RGBA_8888);

    ANativeWindow_Buffer buf;
    if (ANativeWindow_lock(cap->window, &buf, nullptr) != 0) {
        LOGE("ANativeWindow_lock failed");
        return;
    }

    auto* src = static_cast<const uint8_t*>(cap->shmData);
    auto* dst = static_cast<uint8_t*>(buf.bits);
    uint32_t rows = cap->height < static_cast<uint32_t>(buf.height) ? cap->height : static_cast<uint32_t>(buf.height);
    uint32_t cols = cap->width < static_cast<uint32_t>(buf.width) ? cap->width : static_cast<uint32_t>(buf.width);

    for (uint32_t y = 0; y < rows; y++) {
        const uint8_t* srcRow = src + static_cast<size_t>(y) * cap->stride;
        uint8_t* dstRow = dst + static_cast<size_t>(y) * buf.stride * 4;
        for (uint32_t x = 0; x < cols; x++) {
            const uint8_t* p = srcRow + x * 4; // B, G, R, A
            uint8_t* q = dstRow + x * 4;       // R, G, B, A
            q[0] = p[2];
            q[1] = p[1];
            q[2] = p[0];
            q[3] = p[3];
        }
    }

    ANativeWindow_unlockAndPost(cap->window);
}

void frame_buffer(void* data, zwlr_screencopy_frame_v1* /*frame*/, uint32_t format,
                   uint32_t width, uint32_t height, uint32_t stride) {
    auto* cap = static_cast<OutputCapture*>(data);
    // First shm buffer offer wins — we don't negotiate among several.
    if (!cap->haveBufferInfo) {
        cap->format = format;
        cap->width = width;
        cap->height = height;
        cap->stride = stride;
        cap->haveBufferInfo = true;
    }
}

void frame_flags(void* /*data*/, zwlr_screencopy_frame_v1* /*frame*/, uint32_t /*flags*/) {}

void frame_ready(void* data, zwlr_screencopy_frame_v1* frame, uint32_t /*tv_sec_hi*/,
                  uint32_t /*tv_sec_lo*/, uint32_t /*tv_nsec*/) {
    auto* cap = static_cast<OutputCapture*>(data);
    blitFrameToWindow(cap);

    zwlr_screencopy_frame_v1_destroy(frame);
    cap->frame = nullptr;

    if (cap->running) {
        startNextCapture(cap); // continuous loop: immediately request the next frame
    }
}

void frame_failed(void* data, zwlr_screencopy_frame_v1* frame) {
    auto* cap = static_cast<OutputCapture*>(data);
    LOGW("screencopy frame failed");
    zwlr_screencopy_frame_v1_destroy(frame);
    cap->frame = nullptr;

    if (cap->running) {
        startNextCapture(cap); // retry — a single failed frame shouldn't kill the session
    }
}

void frame_damage(void* /*data*/, zwlr_screencopy_frame_v1* /*frame*/, uint32_t /*x*/,
                   uint32_t /*y*/, uint32_t /*width*/, uint32_t /*height*/) {}

void frame_linux_dmabuf(void* /*data*/, zwlr_screencopy_frame_v1* /*frame*/, uint32_t /*format*/,
                         uint32_t /*width*/, uint32_t /*height*/) {
    // Not implemented: this client only ever requests the shm path (see
    // frame_buffer_done, which always allocates a wl_shm buffer) — GPU
    // zero-copy via DMA-BUF is real future work (SPEC.md/README already
    // call this out), not something silently dropped by accident.
}

void frame_buffer_done(void* data, zwlr_screencopy_frame_v1* frame) {
    auto* cap = static_cast<OutputCapture*>(data);
    if (!cap->haveBufferInfo) {
        LOGE("buffer_done with no shm buffer offered — compositor didn't send a wl_shm option");
        zwlr_screencopy_frame_v1_destroy(frame);
        cap->frame = nullptr;
        return;
    }

    allocateShmBuffer(cap);
    if (!cap->buffer) {
        LOGE("failed to allocate shm buffer for screencopy frame");
        zwlr_screencopy_frame_v1_destroy(frame);
        cap->frame = nullptr;
        return;
    }

    zwlr_screencopy_frame_v1_copy(frame, cap->buffer);
}

// A real named object with static storage duration — deliberately NOT a
// function returning a temporary. zwlr_screencopy_frame_v1_add_listener
// stores this pointer for the lifetime of the frame object and Wayland
// calls back into it asynchronously; taking the address of a temporary
// here would leave that callback pointing at already-destroyed stack
// memory the moment the enclosing expression finished.
constexpr zwlr_screencopy_frame_v1_listener kFrameListener = {
    .buffer = frame_buffer,
    .flags = frame_flags,
    .ready = frame_ready,
    .failed = frame_failed,
    .damage = frame_damage,
    .linux_dmabuf = frame_linux_dmabuf,
    .buffer_done = frame_buffer_done,
};

void startNextCapture(OutputCapture* cap) {
    cap->haveBufferInfo = false;
    cap->frame = zwlr_screencopy_manager_v1_capture_output(cap->manager, /*overlay_cursor=*/1, cap->output);
    zwlr_screencopy_frame_v1_add_listener(cap->frame, &kFrameListener, cap);
}

// ---- clipboard (ext-data-control-v1) ----

// Offered in descending preference order; the same UTF-8 bytes are written
// for all of them. The X11-era names (UTF8_STRING/STRING/TEXT) are here
// because Xwayland-hosted applications — which is most Wine software, the
// whole point of the primary container — ask for those and nothing else.
constexpr const char* kOfferedTextMimes[] = {
    "text/plain;charset=utf-8",
    "text/plain",
    "UTF8_STRING",
    "STRING",
    "TEXT",
};

/** Higher is better; -1 means "not text, ignore this offer". */
int textMimeRank(const char* mime) {
    if (std::strcmp(mime, "text/plain;charset=utf-8") == 0) return 4;
    if (std::strcmp(mime, "UTF8_STRING") == 0) return 3;
    if (std::strcmp(mime, "text/plain") == 0) return 2;
    if (std::strcmp(mime, "STRING") == 0) return 1;
    if (std::strcmp(mime, "TEXT") == 0) return 0;
    return -1;
}

/** Per-offer scratch: the best text MIME type seen on it so far. */
struct OfferMimes {
    int rank = -1;
    std::string mime;
};

void offer_offer(void* data, ext_data_control_offer_v1* /*offer*/, const char* mimeType) {
    auto* info = static_cast<OfferMimes*>(data);
    int rank = textMimeRank(mimeType);
    if (rank > info->rank) {
        info->rank = rank;
        info->mime = mimeType;
    }
}

constexpr ext_data_control_offer_v1_listener kOfferListener = {
    .offer = offer_offer,
};

/** Destroys an offer along with the OfferMimes allocated for it. */
void destroyOffer(ext_data_control_offer_v1* offer) {
    if (!offer) return;
    delete static_cast<OfferMimes*>(ext_data_control_offer_v1_get_user_data(offer));
    ext_data_control_offer_v1_destroy(offer);
}

/**
 * Reads one selection transfer to completion and hands the text to the
 * registered sink. Runs detached, and deliberately captures the callback and
 * the fd rather than the ClipboardState pointer: disconnect() can free that
 * state while a transfer is still draining, and a worker that never touches
 * it after being spawned cannot dangle.
 */
struct ReceiveJob {
    int fd = -1;
    ClipboardTextCallback callback = nullptr;
    void* callbackUserData = nullptr;
};

void* clipboardReceiveThread(void* arg) {
    auto* job = static_cast<ReceiveJob*>(arg);

    std::string text;
    char buffer[4096];
    bool overLimit = false;
    for (;;) {
        ssize_t n = read(job->fd, buffer, sizeof(buffer));
        if (n < 0) {
            if (errno == EINTR) continue;
            LOGW("clipboard read from container failed: %s", strerror(errno));
            overLimit = true; // treat a partial read as unusable, not as truncated text
            break;
        }
        if (n == 0) break;
        if (text.size() + static_cast<size_t>(n) > WaylandClient::kMaxClipboardBytes) {
            LOGW("container selection exceeds %zu bytes — dropped rather than truncated",
                 WaylandClient::kMaxClipboardBytes);
            overLimit = true;
            break;
        }
        text.append(buffer, static_cast<size_t>(n));
    }
    close(job->fd);

    if (!overLimit && job->callback && !text.empty()) {
        job->callback(job->callbackUserData, text.data(), text.size());
    }

    delete job;
    return nullptr;
}

/**
 * Writes our offered text into the fd the compositor handed us. Detached and
 * self-contained for the same reason as the read side, plus one of its own:
 * a container-side paste target that opens the pipe and then stalls would
 * otherwise block the dispatch thread indefinitely.
 */
struct SendJob {
    int fd = -1;
    std::string text;
};

void* clipboardSendThread(void* arg) {
    auto* job = static_cast<SendJob*>(arg);

    // A paste target that closes its end early raises SIGPIPE on this
    // thread, whose default disposition kills the whole process. Blocking it
    // here turns that into a plain EPIPE from write(). Thread-directed and
    // thread-local, so this never changes the app's process-wide handling.
    sigset_t blocked;
    sigemptyset(&blocked);
    sigaddset(&blocked, SIGPIPE);
    pthread_sigmask(SIG_BLOCK, &blocked, nullptr);

    const char* cursor = job->text.data();
    size_t remaining = job->text.size();
    while (remaining > 0) {
        ssize_t n = write(job->fd, cursor, remaining);
        if (n < 0) {
            if (errno == EINTR) continue;
            LOGW("clipboard write to container failed: %s", strerror(errno));
            break;
        }
        cursor += n;
        remaining -= static_cast<size_t>(n);
    }
    close(job->fd);

    delete job;
    return nullptr;
}

void spawnDetached(void* (*entry)(void*), void* arg) {
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    pthread_t thread;
    if (pthread_create(&thread, &attr, entry, arg) != 0) {
        LOGE("pthread_create for a clipboard transfer failed: %s", strerror(errno));
    }
    pthread_attr_destroy(&attr);
}

void source_send(void* data, ext_data_control_source_v1* /*source*/, const char* /*mimeType*/,
                  int32_t fd) {
    auto* clip = static_cast<ClipboardState*>(data);
    auto* job = new SendJob();
    job->fd = fd;
    {
        std::lock_guard<std::mutex> lock(clip->mutex);
        job->text = clip->offeredText;
    }
    // Every MIME type we offer carries the same UTF-8 bytes, so which one
    // was asked for doesn't change what gets written.
    spawnDetached(clipboardSendThread, job);
}

void source_cancelled(void* data, ext_data_control_source_v1* source) {
    auto* clip = static_cast<ClipboardState*>(data);
    std::lock_guard<std::mutex> lock(clip->mutex);
    if (clip->source == source) {
        clip->source = nullptr;
    }
    // Cancelled means something else took the selection; the source is dead
    // either way and the protocol expects us to destroy it.
    ext_data_control_source_v1_destroy(source);
}

constexpr ext_data_control_source_v1_listener kSourceListener = {
    .send = source_send,
    .cancelled = source_cancelled,
};

void device_data_offer(void* /*data*/, ext_data_control_device_v1* /*device*/,
                        ext_data_control_offer_v1* offer) {
    // The offer's MIME list arrives as a burst of `offer` events after this
    // one and before the `selection` that names it, so all this does is
    // attach somewhere to collect them.
    ext_data_control_offer_v1_add_listener(offer, &kOfferListener, new OfferMimes());
}

void device_selection(void* data, ext_data_control_device_v1* /*device*/,
                       ext_data_control_offer_v1* offer) {
    auto* clip = static_cast<ClipboardState*>(data);

    destroyOffer(clip->currentOffer);
    clip->currentOffer = offer;

    // A null offer means the selection was cleared. Deliberately NOT
    // mirrored onto Android: wiping what the user has on their phone's
    // clipboard because a container application exited is destructive, and
    // nothing about "the container has no selection" implies they wanted
    // that.
    if (!offer) return;

    auto* info = static_cast<OfferMimes*>(ext_data_control_offer_v1_get_user_data(offer));
    if (!info || info->rank < 0) {
        return; // an image or a file list — this bridge is text-only, by design
    }

    ClipboardTextCallback callback;
    void* callbackUserData;
    {
        std::lock_guard<std::mutex> lock(clip->mutex);
        callback = clip->callback;
        callbackUserData = clip->callbackUserData;
    }
    if (!callback) return;

    int fds[2];
    if (pipe2(fds, O_CLOEXEC) != 0) {
        LOGE("pipe2 for a clipboard transfer failed: %s", strerror(errno));
        return;
    }
    ext_data_control_offer_v1_receive(offer, info->mime.c_str(), fds[1]);
    close(fds[1]);
    // The compositor only starts the transfer once it processes the request
    // above, and this callback runs between dispatches, so nothing would
    // flush it before the reader below started waiting.
    wl_display_flush(clip->display);

    auto* job = new ReceiveJob();
    job->fd = fds[0];
    job->callback = callback;
    job->callbackUserData = callbackUserData;
    spawnDetached(clipboardReceiveThread, job);
}

void device_finished(void* data, ext_data_control_device_v1* device) {
    auto* clip = static_cast<ClipboardState*>(data);
    LOGW("ext_data_control device finished — clipboard bridge is down for this connection");
    clip->finished = true;
    if (clip->device == device) {
        clip->device = nullptr;
    }
    ext_data_control_device_v1_destroy(device);
}

void device_primary_selection(void* /*data*/, ext_data_control_device_v1* /*device*/,
                               ext_data_control_offer_v1* offer) {
    // X11/Wayland's middle-click primary selection has no Android
    // counterpart at all, so it is not bridged. The offer still has to be
    // destroyed — the compositor created it for us either way.
    destroyOffer(offer);
}

constexpr ext_data_control_device_v1_listener kDeviceListener = {
    .data_offer = device_data_offer,
    .selection = device_selection,
    .finished = device_finished,
    .primary_selection = device_primary_selection,
};

} // namespace

// ---- WaylandClient ----

WaylandClient::~WaylandClient() {
    disconnect();
}

namespace {
void* dispatchThreadTrampoline(void* arg) {
    static_cast<WaylandClient*>(arg)->dispatchLoop();
    return nullptr;
}
} // namespace

void WaylandClient::startDispatchThread() {
    dispatchThreadRunning_ = true;
    auto* thread = new pthread_t();
    pthread_create(thread, nullptr, dispatchThreadTrampoline, this);
    dispatchThreadHandle_ = thread;
}

void WaylandClient::stopDispatchThread() {
    if (!dispatchThreadHandle_) return;
    dispatchThreadRunning_ = false;
    // wl_display_dispatch() is blocking (waits on the socket) — in practice
    // disconnect() closing the underlying fd out from under the thread is
    // what actually unblocks it here. Good enough for a first version; a
    // self-pipe/eventfd wakeup would be cleaner and should replace this if
    // shutdown latency ever actually matters.
    auto* thread = static_cast<pthread_t*>(dispatchThreadHandle_);
    pthread_join(*thread, nullptr);
    delete thread;
    dispatchThreadHandle_ = nullptr;
}

void WaylandClient::dispatchLoop() {
    while (dispatchThreadRunning_ && display_) {
        if (wl_display_dispatch(display_) < 0) {
            LOGW("wl_display_dispatch returned error, dispatch thread exiting");
            break;
        }
    }
}

bool WaylandClient::connect(const char* socketPath) {
    int fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (fd < 0) {
        LOGE("socket() failed for %s", socketPath);
        return false;
    }

    sockaddr_un addr{};
    addr.sun_family = AF_UNIX;
    std::strncpy(addr.sun_path, socketPath, sizeof(addr.sun_path) - 1);

    if (::connect(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
        LOGE("connect() failed for %s: %s", socketPath, strerror(errno));
        close(fd);
        return false;
    }

    display_ = wl_display_connect_to_fd(fd);
    if (!display_) {
        LOGE("wl_display_connect_to_fd failed for %s", socketPath);
        close(fd);
        return false;
    }

    globals_ = new WaylandGlobals();
    registry_ = wl_display_get_registry(display_);
    wl_registry_add_listener(registry_, &kRegistryListener, globals_);

    // Round-trip twice: once to receive the initial batch of `global`
    // events, once more so any interface-version-dependent follow-up from
    // binding (none currently, but cheap insurance) is flushed too.
    wl_display_roundtrip(display_);
    wl_display_roundtrip(display_);

    if (!globals_->compositor || !globals_->seat || !globals_->screencopy_manager ||
        !globals_->virtual_pointer_manager || !globals_->virtual_keyboard_manager) {
        LOGE("primary container's compositor is missing a required global "
             "(compositor=%p seat=%p screencopy=%p vptr=%p vkbd=%p) — is vendor/sway "
             "built with the headless backend + these protocols enabled?",
             (void*)globals_->compositor, (void*)globals_->seat,
             (void*)globals_->screencopy_manager, (void*)globals_->virtual_pointer_manager,
             (void*)globals_->virtual_keyboard_manager);
        disconnect();
        return false;
    }
    if (!globals_->shm || !globals_->output) {
        LOGW("compositor advertised no wl_shm or no wl_output yet — screencopy will fail "
             "until presentPrimaryOutput() is retried after one appears");
    }

    // Virtual input devices are created once, up front, and reused for the
    // life of the connection.
    globals_->virtual_pointer = zwlr_virtual_pointer_manager_v1_create_virtual_pointer(
        globals_->virtual_pointer_manager, globals_->seat);
    globals_->virtual_keyboard = zwp_virtual_keyboard_manager_v1_create_virtual_keyboard(
        globals_->virtual_keyboard_manager, globals_->seat);

    // zwp_virtual_keyboard_v1 requires a keymap before it will process any
    // key event at all (protocol requirement, not a hostbridge choice) —
    // see default_keymap.h for why this is a static embedded blob rather
    // than something generated on-device.
    size_t keymapSize = sizeof(kDefaultXkbKeymapUS); // includes the trailing NUL, which is fine/expected
    int keymapFd = ASharedMemory_create("hostbridge-keymap", keymapSize);
    if (keymapFd >= 0) {
        void* dst = mmap(nullptr, keymapSize, PROT_READ | PROT_WRITE, MAP_SHARED, keymapFd, 0);
        if (dst != MAP_FAILED) {
            std::memcpy(dst, kDefaultXkbKeymapUS, keymapSize);
            munmap(dst, keymapSize);
            zwp_virtual_keyboard_v1_keymap(globals_->virtual_keyboard, WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1,
                                            keymapFd, static_cast<uint32_t>(keymapSize));
        } else {
            LOGE("mmap failed for keymap fd: %s", strerror(errno));
        }
        close(keymapFd); // wl_keyboard.keymap request duplicates the fd internally; safe to close ours
    } else {
        LOGE("ASharedMemory_create failed for keymap");
    }

    // Clipboard. Non-fatal when absent, unlike the globals checked above:
    // the desktop is still usable without a selection bridge.
    if (!clipboard_) clipboard_ = new ClipboardState();
    clipboard_->display = display_;
    clipboard_->manager = globals_->data_control_manager;
    if (clipboard_->manager) {
        clipboard_->device = ext_data_control_manager_v1_get_data_device(
            clipboard_->manager, globals_->seat);
        ext_data_control_device_v1_add_listener(clipboard_->device, &kDeviceListener, clipboard_);
        // Flushes the device creation and pulls in whatever selection the
        // compositor is ALREADY holding, so a container-side copy that
        // happened before this connection still reaches Android.
        wl_display_roundtrip(display_);
    } else {
        LOGW("compositor advertised no ext_data_control_manager_v1 — clipboard will not "
             "cross between Android and the container (is vendor/sway built with it?)");
    }

    LOGI("connected to primary container compositor at %s", socketPath);

    startDispatchThread();
    return true;
}

void WaylandClient::disconnect() {
    stopPresenting();
    stopDispatchThread();

    // After the dispatch thread is down, so no callback can be running
    // against this state while it's being torn down. In-flight transfer
    // workers are unaffected on purpose: they hold only an fd and a
    // callback, never this pointer (see ReceiveJob/SendJob).
    if (clipboard_) {
        {
            std::lock_guard<std::mutex> lock(clipboard_->mutex);
            if (clipboard_->source) {
                ext_data_control_source_v1_destroy(clipboard_->source);
                clipboard_->source = nullptr;
            }
        }
        destroyOffer(clipboard_->currentOffer);
        clipboard_->currentOffer = nullptr;
        if (clipboard_->device) {
            ext_data_control_device_v1_destroy(clipboard_->device);
            clipboard_->device = nullptr;
        }
        delete clipboard_;
        clipboard_ = nullptr;
    }

    if (globals_) {
        if (globals_->virtual_pointer) zwlr_virtual_pointer_v1_destroy(globals_->virtual_pointer);
        if (globals_->virtual_keyboard) zwp_virtual_keyboard_v1_destroy(globals_->virtual_keyboard);
    }
    delete globals_;
    globals_ = nullptr;

    if (registry_) {
        wl_registry_destroy(registry_);
        registry_ = nullptr;
    }
    if (display_) {
        wl_display_disconnect(display_);
        display_ = nullptr;
    }
}

bool WaylandClient::presentPrimaryOutput(ANativeWindow* window) {
    if (!globals_ || !globals_->output || !globals_->shm || !globals_->screencopy_manager) {
        LOGE("presentPrimaryOutput: missing output/shm/screencopy_manager global");
        return false;
    }

    stopPresenting();

    capture_ = new OutputCapture();
    capture_->window = window;
    capture_->manager = globals_->screencopy_manager;
    capture_->output = globals_->output;
    capture_->shm = globals_->shm;
    capture_->running = true;

    startNextCapture(capture_);
    return true;
}

void WaylandClient::stopPresenting() {
    if (!capture_) return;

    capture_->running = false;
    if (capture_->frame) {
        zwlr_screencopy_frame_v1_destroy(capture_->frame);
    }
    if (capture_->buffer) wl_buffer_destroy(capture_->buffer);
    if (capture_->pool) wl_shm_pool_destroy(capture_->pool);
    if (capture_->shmData) munmap(capture_->shmData, capture_->shmSize);
    if (capture_->shmFd >= 0) close(capture_->shmFd);

    delete capture_;
    capture_ = nullptr;
}

void WaylandClient::injectPointerMotion(double dx, double dy) {
    if (!globals_ || !globals_->virtual_pointer) return;
    uint32_t timeMs = 0; // 0 lets the compositor timestamp it — fine for injected input
    zwlr_virtual_pointer_v1_motion(globals_->virtual_pointer, timeMs,
                                    wl_fixed_from_double(dx), wl_fixed_from_double(dy));
    zwlr_virtual_pointer_v1_frame(globals_->virtual_pointer);
}

void WaylandClient::injectPointerMotionAbsolute(double x, double y, uint32_t extentWidth, uint32_t extentHeight) {
    if (!globals_ || !globals_->virtual_pointer) return;
    zwlr_virtual_pointer_v1_motion_absolute(
        globals_->virtual_pointer, 0,
        static_cast<uint32_t>(x), static_cast<uint32_t>(y),
        extentWidth, extentHeight);
    zwlr_virtual_pointer_v1_frame(globals_->virtual_pointer);
}

void WaylandClient::injectPointerButton(uint32_t linuxButtonCode, bool pressed) {
    if (!globals_ || !globals_->virtual_pointer) return;
    zwlr_virtual_pointer_v1_button(globals_->virtual_pointer, 0, linuxButtonCode,
                                    pressed ? WL_POINTER_BUTTON_STATE_PRESSED : WL_POINTER_BUTTON_STATE_RELEASED);
    zwlr_virtual_pointer_v1_frame(globals_->virtual_pointer);
}

void WaylandClient::injectPointerAxis(double horizontal, double vertical) {
    if (!globals_ || !globals_->virtual_pointer) return;
    if (horizontal != 0.0) {
        zwlr_virtual_pointer_v1_axis(globals_->virtual_pointer, 0, WL_POINTER_AXIS_HORIZONTAL_SCROLL,
                                      wl_fixed_from_double(horizontal));
    }
    if (vertical != 0.0) {
        zwlr_virtual_pointer_v1_axis(globals_->virtual_pointer, 0, WL_POINTER_AXIS_VERTICAL_SCROLL,
                                      wl_fixed_from_double(vertical));
    }
    zwlr_virtual_pointer_v1_frame(globals_->virtual_pointer);
}

void WaylandClient::injectKey(uint32_t evdevKeyCode, bool pressed) {
    if (!globals_ || !globals_->virtual_keyboard) return;
    zwp_virtual_keyboard_v1_key(globals_->virtual_keyboard, 0, evdevKeyCode,
                                 pressed ? WL_KEYBOARD_KEY_STATE_PRESSED : WL_KEYBOARD_KEY_STATE_RELEASED);
}

void WaylandClient::setClipboardListener(ClipboardTextCallback callback, void* userData) {
    if (!clipboard_) clipboard_ = new ClipboardState();
    std::lock_guard<std::mutex> lock(clipboard_->mutex);
    clipboard_->callback = callback;
    clipboard_->callbackUserData = userData;
}

bool WaylandClient::offerClipboardText(const char* utf8Text, size_t length) {
    if (!utf8Text) return false;
    if (!clipboard_ || !clipboard_->manager || !clipboard_->device || clipboard_->finished) {
        return false;
    }

    if (length > kMaxClipboardBytes) {
        LOGW("refusing to push %zu bytes to the container selection (limit %zu)",
             length, kMaxClipboardBytes);
        return false;
    }

    std::lock_guard<std::mutex> lock(clipboard_->mutex);
    clipboard_->offeredText.assign(utf8Text, length);

    auto* source = ext_data_control_manager_v1_create_data_source(clipboard_->manager);
    ext_data_control_source_v1_add_listener(source, &kSourceListener, clipboard_);
    for (const char* mime : kOfferedTextMimes) {
        ext_data_control_source_v1_offer(source, mime);
    }
    ext_data_control_device_v1_set_selection(clipboard_->device, source);

    // Replaced only after the new claim is on the wire: destroying the old
    // source first would briefly clear the container's selection.
    ext_data_control_source_v1* previous = clipboard_->source;
    clipboard_->source = source;
    if (previous) {
        ext_data_control_source_v1_destroy(previous);
    }

    wl_display_flush(display_);
    return true;
}

} // namespace hostbridge
