#include "wayland_client.h"

#include <android/log.h>
#include <wayland-client.h>

#include <cstring>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

// Generated by wayland-scanner at build time from vendor/wlroots/protocol —
// see ../CMakeLists.txt. Not present until that codegen step has actually
// been run with wayland-scanner on the PATH.
#include "wlr-screencopy-unstable-v1-client-protocol.h"
#include "wlr-virtual-pointer-unstable-v1-client-protocol.h"
#include "virtual-keyboard-unstable-v1-client-protocol.h"

#define LOG_TAG "hostbridge/wl"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace hostbridge {

// Globals bound off the primary container compositor's registry. Every one
// of these is required — if sway (or whatever's running as the primary
// container's compositor) doesn't advertise all four, connect() fails,
// since hostbridge has no fallback path for a compositor missing any of
// them.
struct WaylandGlobals {
    wl_compositor* compositor = nullptr;
    wl_seat* seat = nullptr;
    zwlr_screencopy_manager_v1* screencopy_manager = nullptr;
    zwlr_virtual_pointer_manager_v1* virtual_pointer_manager = nullptr;
    zwp_virtual_keyboard_manager_v1* virtual_keyboard_manager = nullptr;
};

namespace {

void registry_global(void* data, wl_registry* registry, uint32_t name,
                      const char* interface, uint32_t version) {
    auto* globals = static_cast<WaylandGlobals*>(data);

    if (std::strcmp(interface, wl_compositor_interface.name) == 0) {
        globals->compositor = static_cast<wl_compositor*>(
            wl_registry_bind(registry, name, &wl_compositor_interface, 4));
    } else if (std::strcmp(interface, wl_seat_interface.name) == 0) {
        globals->seat = static_cast<wl_seat*>(
            wl_registry_bind(registry, name, &wl_seat_interface, 7));
    } else if (std::strcmp(interface, zwlr_screencopy_manager_v1_interface.name) == 0) {
        globals->screencopy_manager = static_cast<zwlr_screencopy_manager_v1*>(
            wl_registry_bind(registry, name, &zwlr_screencopy_manager_v1_interface, version));
    } else if (std::strcmp(interface, zwlr_virtual_pointer_manager_v1_interface.name) == 0) {
        globals->virtual_pointer_manager = static_cast<zwlr_virtual_pointer_manager_v1*>(
            wl_registry_bind(registry, name, &zwlr_virtual_pointer_manager_v1_interface, version));
    } else if (std::strcmp(interface, zwp_virtual_keyboard_manager_v1_interface.name) == 0) {
        globals->virtual_keyboard_manager = static_cast<zwp_virtual_keyboard_manager_v1*>(
            wl_registry_bind(registry, name, &zwp_virtual_keyboard_manager_v1_interface, version));
    }
}

void registry_global_remove(void* /* data */, wl_registry* /* registry */, uint32_t /* name */) {
    // TODO: handle the primary container's compositor restarting mid-session
    // (a global disappearing) — currently unhandled, connection just goes stale.
}

constexpr wl_registry_listener kRegistryListener = {
    .global = registry_global,
    .global_remove = registry_global_remove,
};

// Opens a UNIX domain socket at an explicit filesystem path and connects it.
// We can't use wl_display_connect(name) here — that resolves a bare socket
// name against THIS process's own $XDG_RUNTIME_DIR, but the compositor
// we're reaching lives inside the primary container's mount namespace, so
// the caller must hand us the socket's real path as seen from outside that
// namespace (however the container runtime exposes it — a bind mount into
// this app's accessible storage, most likely; that plumbing is
// runtime-linux-root/-noroot's responsibility, not this file's).
int connectUnixSocket(const char* path) {
    int fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (fd < 0) {
        LOGE("socket() failed for %s", path);
        return -1;
    }

    sockaddr_un addr{};
    addr.sun_family = AF_UNIX;
    std::strncpy(addr.sun_path, path, sizeof(addr.sun_path) - 1);

    if (::connect(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
        LOGE("connect() failed for %s", path);
        close(fd);
        return -1;
    }

    return fd;
}

} // namespace

WaylandClient::~WaylandClient() {
    disconnect();
}

bool WaylandClient::connect(const char* socketPath) {
    int fd = connectUnixSocket(socketPath);
    if (fd < 0) {
        return false;
    }

    display_ = wl_display_connect_to_fd(fd);
    if (!display_) {
        LOGE("wl_display_connect_to_fd failed for %s", socketPath);
        close(fd);
        return false;
    }

    globals_ = new WaylandGlobals();
    registry_ = wl_display_get_registry(display_);
    wl_registry_add_listener(registry_, &kRegistryListener, globals_);

    // Round-trip twice: once to receive the initial batch of `global`
    // events, once more so any interface-version-dependent follow-up from
    // binding (none currently, but cheap insurance) is flushed too.
    wl_display_roundtrip(display_);
    wl_display_roundtrip(display_);

    if (!globals_->compositor || !globals_->seat || !globals_->screencopy_manager ||
        !globals_->virtual_pointer_manager || !globals_->virtual_keyboard_manager) {
        LOGE("primary container's compositor is missing a required global "
             "(compositor=%p seat=%p screencopy=%p vptr=%p vkbd=%p) — is vendor/sway "
             "built with the headless backend + these protocols enabled?",
             (void*)globals_->compositor, (void*)globals_->seat,
             (void*)globals_->screencopy_manager, (void*)globals_->virtual_pointer_manager,
             (void*)globals_->virtual_keyboard_manager);
        disconnect();
        return false;
    }

    LOGI("connected to primary container compositor at %s", socketPath);

    // TODO (next, not yet implemented): request an output list, start a
    // zwlr_screencopy_manager_v1 capture loop per DisplayOutput, and expose
    // frame delivery back to HostBridge.kt's presentOutput(). See
    // host-bridge/README.md status notes.
    return true;
}

void WaylandClient::disconnect() {
    delete globals_;
    globals_ = nullptr;

    if (registry_) {
        wl_registry_destroy(registry_);
        registry_ = nullptr;
    }
    if (display_) {
        wl_display_disconnect(display_);
        display_ = nullptr;
    }
}

} // namespace hostbridge
